<a href="https://colab.research.google.com/github/MuhammadjonR/Data_Science_Projetcs/blob/main/DL_project_Tabular.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import fastai
import torch

In [10]:
from fastai.tabular.all import *

# dataset
path = untar_data(URLs.ADULT_SAMPLE)

# dataloaders

dls = TabularDataLoaders.from_csv(path/'adult.csv',path=path,bs=64,y_names='salary', skipinitialspace=False,cat_names=['workclass','education','marital-status','occupation','relationship','race','sex'],
                                cont_names=['age','fnlwgt','education-num','capital-gain','capital-loss','hours-per-week'],
                                procs = [Categorify,FillMissing,Normalize])


# train

learn = tabular_learner(dls,metrics=accuracy)
learn.fit_one_cycle(4)

In [15]:
# loading data set into dataframe

import pandas as pd
df = pd.read_csv(path/'adult.csv')
df.head(10)

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,salary
0,49,Private,101320,Assoc-acdm,12.0,Married-civ-spouse,NaN,Wife,White,Female,0,1902,40,United-States,>=50k
1,44,Private,236746,Masters,14.0,Divorced,Exec-managerial,Not-in-family,White,Male,10520,0,45,United-States,>=50k
2,38,Private,96185,HS-grad,NaN,Divorced,NaN,Unmarried,Black,Female,0,0,32,United-States,<50k
3,38,Self-emp-inc,112847,Prof-school,15.0,Married-civ-spouse,Prof-specialty,Husband,Asian-Pac-Islander,Male,0,0,40,United-States,>=50k
4,42,Self-emp-not-inc,82297,7th-8th,NaN,Married-civ-spouse,Other-service,Wife,Black,Female,0,0,50,United-States,<50k
5,20,Private,63210,HS-grad,9.0,Never-married,Handlers-cleaners,Own-child,White,Male,0,0,15,United-States,<50k
6,49,Private,44434,Some-college,10.0,Divorced,NaN,Other-relative,White,Male,0,0,35,United-States,<50k
7,37,Private,138940,11th,7.0,Married-civ-spouse,NaN,Husband,White,Male,0,0,40,United-States,<50k
8,46,Private,328216,HS-grad,9.0,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,40,United-States,>=50k
9,36,Self-emp-inc,216711,HS-grad,NaN,Married-civ-spouse,NaN,Husband,White,Male,99999,0,50,?,>=50k

In [20]:
# test
row, pred, probs = learn.predict(df.iloc[4])
if pred.item()==1:
  print("The salary >= 50K")
elif pred.item()==0:
  print('The salary < 50K')
pred.item(), probs

The salary < 50K

(0, tensor([0.8284, 0.1716]))